base: 
  project: Deep_Learning

raw_data:
  data_src: data_source

load_data:
  num_classes: 4
  raw_data: data_source
  preprossed_data: data/preprossed
  full_path: "Deep Learning/data_source"
train: 
  split_ration: 0.80

model:
  name: VGG19
  trainable: False
  train_path: data/preprocessed/train
  test_path: data/preprocessed/test
  image_size: [255, 255]
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: ['accuracy']
  epochs: 1
  #batch_size: 32
  save_dir: model/trained.h5

img_augment:
  rescalse: 1./255
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True
  batch_size: 32
  class_mode: 'categorical'

model_dir: models

m1flow_config:
  artifact_dir: artifacts
  experiment_name: Deep_Learning_VGG19
  run_name: mlops
  register_model_name: Deep_Learning_model
  remote_server_uri: http://localhost:5000
  